---
vim_plugins:
  - https://github.com/tpope/vim-sensible.git
  - https://github.com/junegunn/fzf.vim.git
  - https://github.com/itchyny/lightline.vim.git
  - https://github.com/terryma/vim-multiple-cursors.git
  - https://github.com/tpope/vim-surround.git
  - https://github.com/scrooloose/nerdtree.git
  - https://github.com/dense-analysis/ale.git
  - https://github.com/airblade/vim-gitgutter.git
