---

- name: Install unattended-upgrades
  become: yes
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - core

- name: Configure automatic security updates
  become: yes
  template:
    src: templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  tags:
    - core

- name: automatically install security updates
  become: yes
  template:
    src: templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20-auto-upgrades
  tags:
    - core
