---

- install git
  apt:
    name: git
    update_cache: yes
    state: latest
  tags:
    - core

- set global git email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  tags:
    - core

- set global git name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  tags:
    - core

  - set default editor
  git_config:
    name: core.editor
    scope: global
    value: vim
