---
- name: Install tmux
  apt:
    name: tmux
    state: latest
    update_cache: yes
  become: yes
  tags:
    - package

- name: Configure tmux settings
  template:
    src: templates/tmux.conf.j2
    dest: /etc/tmux.conf
    owner: root
    group: root
    mode: '0755'
  become: yes
