---
# Instructions from: https://docs.docker.com/install/linux/docker-ce/debian/

- name: Ensure old docker packages are removed
  become: yes
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker 
    - docker-engine 
    - docker.io 
    - containerd 
    - runc
  tags:
    - core

- name: Add dockers official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  tags:
    - core

- name: Get Ubuntu release name
  shell: lsb_release -cs
  register: lsb_release
  tags:
    - core

- debug:
  msg: "{{ lsb_release.stdout_lines }}"
  tags:
    - core

- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable" 
    state: present
    update_cache: yes
  tags:
    - core

- name: Install latest version of docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 0
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
  tags:
    - core

