---

- name: Install useful packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - curl
    - gimp
    - tree
    - deluge
    - cgroup-tools
    - expect
    - net-tools
    - shellcheck
    - speedtest-cli
    - cpu-checker
  tags:
    - essential
    - package
